const experiences={
 customer:{name:"Customer app",icon:"◈",role:"Workspace owner",start:"overview",groups:[
  ["Workspace",[["overview","⌂","Overview"],["calendar","□","Content calendar","preview"],["posts","▧","Posts library","preview"],["composer","✎","Create post","preview"],["studio","✦","Design studio","preview"]]],
  ["Grow",[["campaigns","◌","Campaigns","preview"],["media","◇","Media library","preview"],["copilot","✧","AI Copilot","preview"],["ideas","⚡","Content ideas","preview"],["analytics","↗","Analytics","preview"],["reports","▥","Reports","preview"]]],
  ["Manage",[["social","◎","Social accounts","preview"],["approvals","✓","Approvals","preview"],["team","♙","Team"],["roles","⚿","Roles & permissions"],["brand","B","Brand kit","preview"],["plan","◫","Plan & usage"],["settings","⚙","Settings"]]],
  ["Entry flows",[["customer-signin","→","Customer sign in"],["customer-reset","⚿","Password reset"],["workspace-picker","◈","Workspace picker"],["invitation","✉","Accept invitation"],["no-workspace","○","No workspace"]]]]},
 admin:{name:"Control center",icon:"⌘",role:"Platform owner",start:"admin-overview",groups:[
  ["Platform",[["admin-overview","⌂","Overview"],["workspaces","◈","Workspaces"],["workspace-detail","◇","Workspace detail"],["customers","♙","Customers"],["support","◉","Support mode"]]],
  ["Commercial",[["plans","◫","Plans"],["entitlements","✓","Entitlements"],["billing","$","Billing","future"],["credits","◇","Credits"]]],
  ["AI & providers",[["providers","◎","Providers"],["models","✦","AI models"],["routing","⇄","Routing"],["ai-usage","↗","AI usage"]]],
  ["Operations",[["configuration","⌘","Configuration"],["secrets","⚿","Secrets"],["flags","⚑","Feature flags"],["audit","▥","Audit log"],["health","♡","System health"],["content","✎","Website content","future"]]],
  ["Access",[["admin-signin","→","Admin sign in"],["admin-mfa","⚿","MFA verification"]]]]},
 public:{name:"Public website",icon:"◎",role:"Website visitor",start:"website-home",groups:[
  ["Website",[["website-home","⌂","Home"],["website-features","✦","Features"],["website-copilot","✧","AI Copilot"],["website-calendar","□","Calendar"],["website-publishing","◎","Publishing"],["website-analytics","↗","Analytics"]]],
  ["Explore",[["website-templates","▧","Templates"],["website-integrations","◇","Integrations"],["website-pricing","$","Pricing"],["website-resources","▥","Resources"],["website-about","B","About"],["website-contact","✉","Contact"]]],
  ["Account",[["website-login","→","Sign in"],["website-signup","+","Start free"]]],
  ["Legal & trust",[["website-privacy","⚿","Privacy"],["website-terms","▥","Terms"],["website-status","♡","Status"]]]
 ]}
};
const meta={overview:["Workspace","Good morning, Mohamed"],calendar:["Plan","Content calendar"],posts:["Library","Posts"],composer:["Create","New post"],studio:["Create","Design studio"],campaigns:["Organise","Campaigns"],media:["Library","Media"],copilot:["AI workspace","Copilot"],ideas:["AI workspace","Content ideas"],analytics:["Measure","Analytics"],reports:["Measure","Reports"],social:["Channels","Social accounts"],approvals:["Workflow","Approvals"],team:["Workspace","Team"],roles:["Workspace","Roles & permissions"],brand:["Workspace","Brand kit"],plan:["Account","Plan & usage"],settings:["Account","Settings"],"admin-overview":["Control center","Platform overview"],workspaces:["Customers","Workspaces"],customers:["Customers","Customer directory"],support:["Security","Support mode"],plans:["Commercial","Plans"],entitlements:["Commercial","Entitlements"],billing:["Commercial","Billing"],credits:["Commercial","Credit ledger"],providers:["AI infrastructure","Providers"],models:["AI infrastructure","Model registry"],routing:["AI infrastructure","Task routing"],"ai-usage":["AI infrastructure","Usage & margin"],configuration:["Platform","Configuration"],secrets:["Security","Secret vault"],flags:["Platform","Feature flags"],audit:["Security","Audit log"],health:["Operations","System health"],content:["Website","Content manager"],"website-home":["Public website","Home"],"website-features":["Public website","Features"],"website-copilot":["Public website","AI Copilot"],"website-calendar":["Public website","Content calendar"],"website-publishing":["Public website","Social publishing"],"website-analytics":["Public website","Analytics"],"website-templates":["Public website","Templates"],"website-integrations":["Public website","Integrations"],"website-pricing":["Public website","Pricing"],"website-resources":["Public website","Resources"],"website-about":["Public website","About"],"website-contact":["Public website","Contact"],"website-login":["Account","Sign in"],"website-signup":["Account","Create account"],map:["Product blueprint","Every page & feature"]};
Object.assign(meta,{"customer-signin":["Customer access","Sign in"],"customer-reset":["Customer access","Reset password"],"workspace-picker":["Customer access","Choose a workspace"],invitation:["Customer access","Accept invitation"],"no-workspace":["Customer access","No workspace"],"workspace-detail":["Customers","Workspace detail"],"admin-signin":["Platform access","Admin sign in"],"admin-mfa":["Platform access","MFA verification"],"website-privacy":["Legal","Privacy"],"website-terms":["Legal","Terms"],"website-status":["Trust","System status"]});
let state={mode:"customer",view:"overview",collapsed:false,lang:"en"};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const appShell=$("#appShell"),navList=$("#navList"),view=$("#view"),sidebar=$("#sidebar");
const button=(label,target,cls="dark-button")=>`<button class="${cls}" ${target?`data-view-target="${target}"`:""}>${label}</button>`;
const metric=(label,value,sub="")=>`<article class="metric"><span>${label}</span><strong>${value}</strong><small>${sub}</small></article>`;
const postRow=(id,title,channel,status="Ready",thumb="")=>`<button class="list-item" data-post-id="${id}"><span class="thumb ${thumb}"></span><span class="item-copy"><b>${title}</b><small>${channel}</small></span><span class="status ${status==="Review"?"review":status==="Draft"?"draft":""}">${status}</span></button>`;
function navMarkup(){return experiences[state.mode].groups.map(([group,items])=>`<div class="nav-group"><span class="nav-group-title">${group}</span>${items.map(([id,icon,label,badge])=>`<button class="nav-item ${state.view===id?"active":""}" data-view-target="${id}" data-label="${label}" ${state.view===id?'aria-current="page"':""}><span class="nav-icon">${icon}</span><span>${label}</span>${badge?`<em class="nav-badge">${badge}</em>`:""}</button>`).join("")}</div>`).join("")}
function setMode(mode){state.mode=mode;state.view=experiences[mode].start;$("#experienceName").textContent=experiences[mode].name;$("#experienceIcon").textContent=experiences[mode].icon;$("#profileRole").textContent=experiences[mode].role;$("#experienceMenu").classList.remove("open");render();closeMobile()}
function showView(id){state.view=id;render();closeDrawer();closeMobile();history.replaceState(null,"",`#${state.mode}/${id}`);window.scrollTo({top:0,behavior:"smooth"})}
function render(){navList.innerHTML=navMarkup();const [eye,title]=meta[state.view]||[experiences[state.mode].name,state.view];$("#pageEyebrow").textContent=eye;$("#pageTitle").textContent=title;view.innerHTML=page(state.view);bindPage()}